version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  post-service:
    build:
      context: ./post-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/postdb
    depends_on:
      - mongo

  like-service:
    build:
      context: ./like-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/likedb
    depends_on:
      - mongo

  comment-service:
    build:
      context: ./comment-service
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/commentdb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  mongo-data:
